const devMode = __DEV__;

// Development Server...
// const baseUrl = !devMode
//   ? 'https://devapi.oceanaut.ca/v1/'
//   : 'https://devapi.oceanaut.ca/v1/';

// const server = 'https://dev.oceanaut.ca';

// Stagin Server...
// const baseUrl = !devMode
//   ? 'https://stagingapi.oceanaut.ca/v1/'
//   : 'https://stagingapi.oceanaut.ca/v1/';

// const server = 'http://staging.oceanaut.ca/';

// Production Server...
const baseUrl = !devMode
  ? 'https://api.oceanaut.ca/v1/'
  : 'https://api.oceanaut.ca/v1/';

const server = 'https://oceanaut.ca/';

const BaseSetting = {
  name: 'Oceanaut',
  displayName: 'Oceanaut',
  appVersionCode: '1',
  stripeKey: '',
  bugsnagApiKey: '',
  baseUrl,
  api: baseUrl,
  shareEndPoint: baseUrl,
  timeOut: 30000,
  MAPS_API_CALL_KEY: '',
  vesselLiveLocation: '708dbabc-9bb2-4f81-bf76-b365cbfbc159',
  liveLocationUrl: 'https://api.datalastic.com/api/v0/',
  googleLoginClientId:
    '875480711780-iqq5uihntntvvgm6e9hafr0dgqlfb1cg.apps.googleusercontent.com',
  emailRegex:
    /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
  endpoints: {
    signup: 'user/sign-up',
    signin: 'user/login',
    forgotPassword: 'user/forgot-password',
    logout: 'user/user-logout',
    activityLogList: 'user/get-activity',
    userDetail: 'user/detail',
    googleLogin: 'user/google-login',
    dashBoardList: 'dashboard-master/dynamic-chart-data',
    dashboardExport: 'dashboard-master/dynamic-dashboard-export',
    dynamicDashList: 'dashboard-master/all-dashboard-list',
    saveFcmToken: 'user/notification-token',
    // signatureModal: 'https://dev.oceanaut.ca/signature-canvas',
    signatureModal: `${server}/signature-canvas`,
    // Dashboard
    // Compliance
    staticVesselDashboard: 'vessels/vessel-certificate-count',
    vesselCount: 'vessels/vessels-count',
    auditCount: 'vessels/audit-count',
    deficiencyCount: 'vessels/deficiency-count',
    tripCount: 'static-dashboard/get-trip-data',
    voyageTime: 'static-dashboard/get-voyage-time',
    totalVessselCount: 'static-dashboard/get-off-service-vessel-data',
    auditBrackdown: 'vessels/audit-break',
    certiExport: 'vessels/vessel-certificate-export',
    vesselDashExport: 'vessels/vessels-count-export',
    auditDashExport: 'vessels/audit-count-export',
    auditBrakeExport: 'vessels/audit-break-export',
    defiencyDashExport: 'vessels/deficiency-count-export',
    // Vessel Dash
    voyageReportCount: 'static-dashboard/get-voyage-reporting-data',
    vesselDashCount: 'static-dashboard/get-vessel-data',
    exportVesselDash: 'static-dashboard/vessel-dashboard-export',
    voyageDashExport: 'static-dashboard/voyage-reporting-dashboard-export',
    tripDashExport: 'static-dashboard/trip-dashboard-export',
    voyagetimeExport: 'static-dashboard/voyage-time-export',
    outofserviceExport: 'static-dashboard/off-service-vessel-export',
    // Map Dash
    staticMap: 'static-dashboard/get-map-data',
    mapFilter: 'static-dashboard/get-trip-ids',
    // LMS Dashboard
    categoryCount: 'static-dashboard/get-lms-category-count',
    roleCourseList: 'static-dashboard/get-role-course',
    courseDashExport: 'static-dashboard/lms-category-count-export',
    trainingDashExport: 'static-dashboard/get-role-course-export',
    // HSEQ Dashboard
    documentCount: 'hseq-dashboard/get-document-data',
    formReporting: 'hseq-dashboard/get-forms-reporting-data',
    searchDocName: 'hseq-dashboard/get-search-documents',
    hseqDynamicForm: 'hseq-dashboard/get-dynamic-menu-data',
    docExport: 'hseq-dashboard/hseq-document-export',
    reportingExport: 'hseq-dashboard/reporting-forms-export',
    hseqmenuExport: 'hseq-dashboard/dynamic-menu-export',
    // Personnel Dashboard
    personnelExport: 'personnel-dashboard/user-account-export',
    backgroundImage: 'admin/get-background-image',
    // Update Profile
    editProfile: 'user/edit-profile',
    uploadphoto: 'common/upload-image',
    fisheriesIdentification:
      'fishery-identification/fishery-identification-update',
    organisationDetail: 'user/organization-detail',
    changePassword: 'change-password/change-password-update',
    signatureUpdate: 'signature/update-user-sign',
    signatureList: 'signature/get-signature-module-list',
    signaturePendingCount: 'signature/get-pending-signature-count',
    // Trip List
    tripList: 'trip/trip-list',
    myTripList: 'trip/my-trip-list',
    tripDetail: 'trip/my-trip-detail',
    formList: 'trip/my-forms-list',
    deleteTrip: 'trip/trip-delete',
    trackingTrip: 'trip/get-trip-tracker-detail',
    endTrip: 'trip/end',
    startTrip: 'trip/start',
    tripImport: 'trip/trip-export',
    tripJson: 'trip/get-json',
    tripTabledata: 'database-generation/table-data',
    createTripJson: 'custom-forms/get-json',
    tripCreate: 'trip/trip-create',
    tripFormUpadate: 'trip/my-form-update',
    tripFormSubmit: 'trip/my-form-submit',
    selectCrewMember: 'trip/check-user',
    checkTripAvailable: 'trip/check-vessel',
    getPortLocation: 'ports/get-port-location',
    locationtrack: 'vessel-tracker/save-tracker-response',
    offlineTripDelete: 'trip/offline-trip-delete',
    // Configuration
    positionList: 'configuration/position-list',
    departmentList: 'configuration/department-list',
    locationList: 'configuration/location-list',
    addPostion: 'configuration/add-position',
    updatePostion: 'configuration/update-position',
    deletePosition: 'configuration/delete-position',
    updateDepartment: 'configuration/update-department',
    addDepartment: 'configuration/add-department',
    deleteDepartment: 'configuration/delete-department',
    updateLocation: 'configuration/update-location',
    addLocation: 'configuration/location-create',
    deleteLocation: 'configuration/delete-location',
    notificationDetailList: 'common/get-notification-matrix-data',
    notificationUpdate: 'common/notification-matrix-update',
    notificationCreate: 'common/notification-matrix-create',
    readAllNotification: 'common/read-normal-notification',
    // Vessel Management
    vesselType: 'vessels-type/vessels-type-list',
    deleteVesselType: 'vessels-type/vessels-type-delete',
    updateVesselType: 'vessels-type/vessels-type-update',
    createVesselTypes: 'vessels-type/vessels-type-create',
    vessel: 'vessels/vessel-list',
    vesslList: 'vessels/audit-form-list',
    categoryList: 'custom-category/lists',
    deficienciesList: 'vessels/punch-list',
    portofDeparture: 'database-generation/table-data',
    deleteDrill: 'vessels/audit-delete',
    scheduleList: 'vessels/audit-schedule-list',
    voyageForm: 'trip/get-form-json',
    selectedForm: 'vessel-forms/lists',
    deficiencyView: 'vessels/deficiency-comment-list',
    viewVessel: 'vessels/vessel-view',
    vesselCertificate: 'vessels/vessel-certificate-list',
    vesselDocument: 'vessels/vessel-document-list',
    vesselDownload: 'vessels/audit-pdf-download',
    deletevesselList: 'vessels/vessel-delete',
    vesselExport: 'vessels/export',
    deficiencyExport: 'vessels/punch-export',
    downloadVesselSample: 'vessels/download-vessel-xlsx',
    importVessel: 'vessels/import-vessels-xlsx',
    createVessel: 'vessels/creates',
    createDeficiency: 'vessels/create-deficiency',
    createAuditDeficiency: 'vessels/deficiency-create',
    deficiencyStatus: 'vessels/deficiencies-status',
    vesselAuditUpdate: 'vessels/audit-update',
    getVesselJson: 'vessels/get-json',
    deleteVesselCertificate: 'vessels/vessel-delete-certificate',
    vesseCertificateUpdate: 'vessels/vessel-update-certificate',
    vesseCertificateCreate: 'vessels/vessel-upload-certificate',
    vesselDocumentCreate: 'vessels/vessel-upload-document',
    deficienciesJson: 'vessels/deficiencies-json',
    drillsStartJson: 'vessels/audit-create',
    drillsEditjson: 'vessels/get-audit-json',
    drillTrackerExport: 'vessels/drill-tracker-export',
    vesselDeficiencyList: 'vessels/deficiency-list',
    deleteVesselDeificiency: 'vessels/deficiency-delete',
    deleteDocument: 'vessels/vessel-delete-document',
    closeForm: 'vessels/change-status',
    deficienciescommentCreate: 'vessels/deficiency-comment-create',
    auditExport: 'vessels/audit-inspection-export',
    drillExport: 'vessels/drill-data-export',
    vesselLiveLocationdata: 'vessel-tracker/vessel-live-location',
    offlineChangeStatus: 'vessels/offline-change-status',
    vesselcrewList: 'trip-module/vessel-crew-list',
    changeMaster: 'trip-module/update-master-status',
    deleteCrewMember: 'trip-module/delete-crew',
    // punchList: "vessels/get-punch-list",
    //
    userManuals: 'admin/user-manuals',
    userManualsDownLoad: 'admin/manuals-download',
    exportList: 'user/export-list',
    exportListDownLoad: 'user/export-download',
    // subscription
    subScriptionList: 'payment/get-active-subscription',
    subScriptionDownload: 'payment/download-invoice',
    mySubscription: 'payment/get-subscription-list',
    subScriptionDetailList: 'payment/get-transaction-list',

    // Elog Preference
    portList: 'ports/user-port-list',
    getCountryPort: 'ports/get-port-list',
    portCountryList: 'ports/list-country',
    allPortList: 'ports/port-list?allData=1',
    updatePort: 'ports/user-port-update',
    createPort: 'ports/user-port-create',
    deletePort: 'ports/user-port-delete',
    portExport: 'ports/user-port-export',
    downloadPortSample: 'ports/download-ports-xlsx',
    importGearType: 'gear-types/import-gear-types-xlsx',
    importFishingArea: 'fishing-areas/import-fishing-area-xlsx',
    importPorts: 'ports/import-ports-xlsx',

    // Personnel
    uploadImage: 'training-tracker/upload-images',
    uploadpersonalCertificate: 'personnel-certificates/upload-images',
    seatimeTrackerList: 'trip/sea-time-tracker-lists',
    trainingTrackerList: 'training-tracker/list',
    drillTrackerList: 'vessels/drill-tracker-list',
    drillFormList: 'vessels/drill-form-list',
    drillAddForm: 'vessels/update-user-data',
    createTrainingTracker: 'training-tracker/creates',
    deleteTrainingTracker: 'training-tracker/deletes',
    updateTrainingTracker: 'training-tracker/updates',
    personnelCertificate: 'personnel-certificates/list',
    assignUserList: 'vessels/assign-user',
    createPersonalCertificate: 'personnel-certificates/creates',
    updatePersonalCertificates: 'personnel-certificates/updates',
    deleteCertificate: 'personnel-certificates/deletes',
    seatimeTrackerExport: 'trip/sea-time-tracker-export',
    trainingTrackerExport: 'training-tracker/training-tracker-export',
    certificateExport: 'personnel-certificates/personnel-certificate-export',
    //User Management
    userList: 'user-list/users-list',
    allRoleList: 'user/role-management-list',
    userCreate: 'user/creates',
    userRoleList: 'user-role-list',
    UserUpdate: 'user/updates',
    UserListView: 'user/views',
    resendEmail: 'user/resend-email',
    exportUser: 'user/user-export-csv',
    downloaduserSample: 'user/download-user-xlsx',
    importUser: 'user/import-user-xlsx',
    // Fisheries ELOG
    fisheriesFormList: 'fisheries-form/lists',
    downloadFisheriesForm: 'fisheries-form/download-fisheries-form',
    downloadMarinemammal: 'marine-mamal-interaction/download-marine-mammal',
    downloadInacivityReport: 'inactivity-report/download-inactivity-report',
    marineMammal: 'marine-mamal-interaction/marine-list',
    createMarineMammal: 'marine-mamal-interaction/marine-create',
    inactivityReport: 'inactivity-report/inactivity-list',
    deleteFishries: 'fisheries-form/deletes',
    deleteMarine: 'marine-mamal-interaction/marine-delete',
    deleteInactivity: 'inactivity-report/inactivity-delete',
    createInactivity: 'inactivity-report/inactivity-create',
    createFisheriesForm: 'fisheries-form/creates',
    getFisheriesFormJson: 'fisheries-form/get-json',
    getMammalFormJson: 'marine-mamal-interaction/get-json',
    getInactivityReportJson: 'inactivity-report/get-json',
    closeConformation: 'marine-mamal-interaction/close',
    //Voyage Reporting
    voyageList: 'vessels/voyage-list',
    voyagedownload: 'vessels/voyage-report-pdf-download',
    voyageEditJson: 'trip/trip-form-json',
    deleteVoyage: 'vessels/voyage-reporting-delete',
    //
    agreementList: 'cms/cms-list',
    //Role Management
    roleList: 'user/role-management-list',
    getRolePermissionJson: 'user/role-json-list',
    deleteRoleManagement: 'user/role-delete',
    createRoleForm: 'user/role-create',
    updateRoleForm: 'user/role-update',
    roleExport: 'user/export-csv',
    // Notification
    notificationList: 'common/get-notification',
    readNotification: 'common/notification-change-status',
    //How to Video
    howToVideoList: 'how-to-videos/videos-list',
    howToVideoCategory: 'how-to-category/category',
    //FORM =====>
    generalForm: 'custom-forms/custom-form-list',
    customFormView: 'custom-forms/custom-form-view',
    delteUploadImages: 'custom-forms/remove-image',
    deficiencyFormView: 'custom-forms/deficiency-form-list',
    goalFormList: 'custom-forms/deficiency-form-list',
    //safteyForm
    safteyFormList: 'safety-management-system/safety-menu-list',
    addSafteyForm: 'safety-management-system/add-menu',
    updateSafteyForm: 'safety-management-system/update-menu',
    deleteSafteyMenu: 'safety-management-system/delete-menu',
    safteyCategoryList: 'custom-category/lists',
    addCategoryForm: 'custom-category/creates',
    deleteCategoryForm: 'custom-category/deletes',
    updatecategoryform: 'custom-category/updates',
    //safteyvesselform
    safteyvessellist: 'custom-forms/vessel-forms',
    deleteForm: 'custom-forms/clone-delete',
    //AuditReportForm
    auditCategoryList: 'custom-category/lists',
    createAuditCategory: 'custom-category/creates',
    updateAuditCategory: 'custom-category/updates',
    deleteAuditCategory: 'custom-category/deletes',
    //commonForms
    commonFormList: 'custom-forms/vessel-forms',
    deleteCommonForm: 'custom-forms/clone-delete',
    customFormUpload: 'custom-forms/upload-image',
    //commonvesselsform
    commonVesselList: 'vessel-forms/lists',
    deleteCommonVessel: 'vessel-forms/deletes',
    vesseldata: 'vessels/vessel-list',
    createVesselForm: 'vessel-forms/creates',
    editVesselForm: 'vessel-forms/updates',

    // announcements
    announcementList: 'announcement/announcement-list',
    //lms
    performanceEvalutionList: 'user/evolution-form-list',
    performanceEvalutionCategory: 'custom-category/lists',
    performanceUserList: 'user-list/users-list',
    performanceStatus: 'user/evalution-list',
    updateEvaluationForm: 'user/evolution-update',
    closeEvaluationForm: 'user/evalution-change-status',
    myEvaluationList: 'user/evolutions-list',
    userEvaluationList: 'user/evoluation-form-list',
    goalList: 'user/goal-list',
    goalJson: 'user/goal-json',
    createGoalForm: 'user/create-goal',
    deleteGoalList: 'user/goal-delete',
    goalView: 'user/goal-comment-list',
    goalcommentCreate: 'user/goal-comment-create',
    goalStatus: 'user/goal-status',
    goalExport: 'user/goal-export',
    createGoalFormList: 'user/goal-create',
    lessonTracker: 'lesson-tracker-create',
    roleFormList: 'user/evalution-forms-lists',
    updateEvalutionForm: 'user/evalution-forms-updates',
    createEvalutionForm: 'user/form-evalution-creates',
    deleteEvalutionForm: 'user/evalution-forms-deletes',
    //lms
    perfomanceUserDetails: 'user/user-evalution-list',
    userEvaluationCreate: 'user/user-evaluation-create',
    courseList: 'lms-course/lists',
    trainingMetrixList: 'training-matrix/lists',
    trainingMetrixCreate: 'training-matrix/creates',
    metrixExport: 'training-matrix/training-matrix-export',
    readAnnouncement: 'announcement/announcement-read',
    quizDetail: 'lms-course/quiz-detail',
    startQuiz: 'lms-course/start-quiz',
    nextQuiz: 'lms-course/update-question-answer',
    previousQuiz: 'lms-course/previous-question-detail',
    getQuizDetails: 'lms-course/get-quiz-detail',
    quizQuestionList: 'lms-course/quiz-question-list',
    finalQuiz: 'lms-course/complete-quiz',
    deleteSectionQuiz: 'lms-course/delete-quiz',
    evaluationSchduleList: 'user/evolution-schedule-list',
    evaluationStartJson: 'user/evoluation-create',
    evalutionEditJson: 'user/get-evolution-json',
    evalutionGoalList: 'user/evolution-goal-list',
    evaluationDownload: 'user/evolution-pdf-download',
    deletePerformanceList: 'user/evalution-delete',
    videoTracking: 'lms-lesson/lesson-tracker-create',
    downloadQuizCertificate: 'lms-course/quiz-certificate-download',
    // END

    //RoleManagementList
    roleManagementList: 'user/role-management-list',
    downloadRoleSampleFile: 'user/download-role-xlsx',
    importRoleManagement: 'user/import-role-xlsx',
    clonePermission: 'role-module/clone-role-data',

    // HSEQ =====>
    //ManageHeader
    headerList: 'safety-management-system/header-list',
    createHeaderList: 'safety-management-system/header-create',
    subHeaderList: 'safety-management-system/sub-header-list',
    subHeaderDropDownList: 'safety-management-system/header-dropdown-list',
    createsubheaderList: 'safety-management-system/sub-header-create',
    menuList: 'safety-management-system/menu-list',
    subheadereMenuList: 'safety-management-system/sub-header-dropdown-list',
    createMenuList: 'safety-management-system/menu-create',
    deleteHeaderList: 'safety-management-system/header-delete',
    deleteSubheaderlist: 'safety-management-system/sub-header-delete',
    deleteMenuList: 'safety-management-system/menu-delete',
    updateHeaderList: 'safety-management-system/header-update',
    updateSubheaderList: 'safety-management-system/sub-header-update',
    updateMenuList: 'safety-management-system/menu-update',
    documentList: 'safety-management-system/document-list',
    createUploadDoc: 'safety-management-system/safety-document-create',
    deleteSafetyDoc: 'safety-management-system/safety-document-delete',
    downloadSafettyDoc: 'safety-management-system/safety-document-download',
    addBookMark: 'safety-management-system/safety-document-bookmark',
    historyRestore: 'safety-management-system/safety-document-restore',
    //SubMenu
    submenuList: 'safety-management-system/sub-menu-list',
    createSubmenuDropDownList: 'safety-management-system/menu-dropdown-list',
    createSubmenuList: 'safety-management-system/sub-menu-create',
    updateSubmenuList: 'safety-management-system/sub-menu-update',
    deleteSubmenuList: 'safety-management-system/sub-menu-delete',
    checkCreateSubmenu: 'safety-management-system/sub-menu-dropdown-list',
    treeList: 'safety-management-system/safety-tree',
    safetyDocList: 'safety-management-system/safety-document-list',
    safetyDocComments: 'safety-management-system/safety-document-history',
    safetyHistoryList: 'safety-management-system/document-chat-list',
    safetyDocView: 'safety-management-system/safety-document-view',
    resolveCommit: 'safety-management-system/document-chat-complete',
    commentCreate: 'safety-management-system/document-chat-create',
    revokeAccess: 'safety-management-system/document-user-uninvite',
    invitationSent: 'safety-management-system/document-user-invite',
    updateStatus: 'safety-management-system/document-review-update',
    publishDoc: 'safety-management-system/safety-document-publish',
    unpublishDoc: 'safety-management-system/safety-document-publish',
    safetyMenuFormSubmit: 'safety-management-system/menu-form-submit',
    safetyDocData: 'safety-management-system/safety-document-data',
    filterCategoryList: 'safety-management-system/get-category-list',
    filterFormlist: 'safety-management-system/get-form-list',
    deleteSafetyForm: 'safety-management-system/form-delete',
    safetyDownload:
      'safety-management-system/download-safety-management-system-pdf',
    safetyAddJson: 'trip/get-form-json',
    safetyEditJson: 'safety-management-system/menu-form-json',
    closeMenuForm: 'safety-management-system/change-status',
    closureFormList: 'safety-management-system/closer-form-list',
    openClosureForm: 'custom-forms/get-closer-json',
    closeSubmitForm: 'custom-forms/closer-form-submit',

    //Text Document
    updateDocument: 'safety-management-system/safety-document-update',

    //END

    //delete accounts
    deleteCompanyData: 'user/delete-company-data',
    deleteUserData: 'user/delete-user-data',

    //user-calender
    userCalnder: 'user/user-calender',
    calenderList: 'user/user-calender-detail',

    //Revert History
    revertHistory: 'vessels/revert-form-list',
    revertForm: 'vessels/revert-form',
    viewRevertForm: 'vessels/revert-form-detail',
    //LMS
    createManageCategory: 'lms-category/lms-category-create',
    manageCategoriesList: 'lms-category/lms-category-list',
    updateCategory: 'lms-category/lms-category-update',
    uploadCategoryImage: 'lms-category/upload-image',
    //LMS Courses
    myLearningData: 'lms-course/learning-course',
    LMSCourseList: 'lms-course/lists',
    deleteCourse: 'lms-course/deletes',
    createManageCourse: 'lms-course/creates',
    mendatoryCourse: 'lms-course/mandatory-course-list',
    optionalCourse: 'lms-course/optional-course-list',
    courseHistory: 'lms-course/get-course-history',
    exportManageCourse: 'lms-course/course-export-csv',
    stripCoursePayment: 'payment/get-stripe-course-session',
    //LMS Section List
    sectionList: 'lms-course/section-list',
    CreateSectionList: 'lms-course/section-create',
    CreateLesson: 'lms-lesson/lms-lesson-create',
    createAllCourse: 'lms-course/all-course',

    changeStatus: 'lms-course/section-change-status',
    //LMS Detail
    courseDetail: 'lms-course/detail',
    courseCategoryList: 'lms-category/lms-category-list',
    removeImage: 'lms-course/remove-doc',
    uploadCourseImage: 'lms-course/upload-image',
    submitCourseDetail: 'lms-course/updates',
    deleteLMSCourse: 'lms-course/deletes',
    courseDataList: 'lms-course/section-list',
    //Edit Lesson
    editLesson: 'lms-lesson/lms-lesson-detail',
    uploadLessonPdf: 'lms-lesson/upload-image',
    uploadVideo: 'lms-lesson/upload-video',
    deleteLessonDocument: 'lms-lesson/remove-image',
    DownloadLMSFile: 'lms-lesson/download-document',
    uplaodLessonEdit: 'lms-lesson/lms-lesson-update',
    lessonDelete: 'lms-lesson/lms-lesson-delete',

    //Edit Course
    courseUpdate: 'lms-course/section-update',

    //End
    deleteCategoryList: 'lms-category/lms-category-delete',

    //section Quiz
    quizDetailList: 'lms-course/quiz-detail',
    createSectionQuiz: 'lms-course/create-quiz',
    createQuizQuestion: 'lms-course/create-quiz-question',
    updateQuizQuestion: 'lms-course/update-quiz-question',
    questionList: 'lms-course/question-list',
    deleteQuizDetail: 'lms-course/delete-quiz-question',
    //lesson Detail
    lessonDetail: 'lms-course/detail',
  },
  passphrase: 'c919055c-9ddf-412b-9f5e-7078ef17ed0a',

  geolocationOptions: {
    enableHighAccuracy: false,
    timeout: 50000,
    maximumAge: 10000,
    distanceFilter: 1,
  },
  geoOptionHighAccurate: {
    enableHighAccuracy: true,
    timeout: 10000,
    maximumAge: 10000,
    distanceFilter: 1,
  },
};

export default BaseSetting;
